version: '3.8'

services:
  geyser-viewer:
    image: hitchbot/geyser-viewer
    container_name: geyser-viewer
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - TZ=America/Denver
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s